server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-locations: file://C:\workspace\native-file-repo
          search-locations: file:///${user.home}/Desktop/Work/native-file-repo
        git:
#          uri: file://C:\workspace\git-local-repo
          uri: https://github.com/1sun0901/spring-cloud-config.git
#          username: emuce@naver.com
#          password: Dlantm3837!